### ISSUE TITLE
Module not found: Can't resolve 'beautiful-react-diagrams/styles.css'

### ISSUE THREAD

**Issue by tinspham209** [antonioru/beautiful-react-diagrams#20]
I was installation with npm. After that, i'm import style to root `src/index.js` : `import 'beautiful-react-diagrams/styles.css';`

and issues: 
`Module not found: Can't resolve 'beautiful-react-diagrams/styles.css' in 'D:\Study\React\mastering-dnd\src'
`

**Comment by antonioru** [comment]
Hello @tinspham209 

thank you for pointing this out, I recently changed the build setup and I must have messed up with the `dist` directory. 

I'm going to solve this as soon as possibile!  

For the moment, as a workaround, try importing the styles like this:

```
import 'beautiful-react-diagrams/dist/styles.css';
```

By doing so you will be importing the correct style. 

Please be aware from the next release (0.3.0) the standard import will be back again, so this is a temporary workaround

**Comment by antonioru** [comment]
@tinspham209 please try to install the library again, importing the style should work now 

'beautiful-react-diagrams/styles.css'
