### ISSUE TITLE
Add CSS color to individual flow lines

### ISSUE THREAD

**Issue by P3GLEG** [antonioru/beautiful-react-diagrams#3]
Awesome diagrams, they are so useful.

Looking through the src Link.js, it doesn't appear to be any way to pass down the CSS to the proper link or add/select them by individual ID. 

```javascript
<g className={classList}>
      <path d={path} className="bi-link-ghost" onDoubleClick={onDoubleClick} />
      <path d={path} ref={pathRef} className="bi-link-path" onDoubleClick={onDoubleClick} />
      {link.label && labelPosition && (<LinkLabel position={labelPosition} label={link.label} />)}
    </g>
```

Is it possible to add an attribute to individual lines to color them? Something like 

```javascript
 [
{ input: 'node-1',  output: 'node-2', label: 'Link 1', color: 'red', readonly: true },
{ input: 'node-1',  output: 'node-3', label: 'Link 2', color: '#008000', readonly: true }
]
```

**Comment by antonioru** [comment]
Hi @P3GLEG ,

Sorry for the late response and thank you for your request. 

The idea behind `beautiful-react-diagrams` is that you can use CSS to customise any style... in future I'll get rid of Tailwind providing a themed CSS styles, but for the moment a good improvement would - perhaps - be to add the `className` attribute to the Links, what do you say?

**Comment by P3GLEG** [comment]
No worries at all. That would be awesome man.

**Comment by antonioru** [comment]
@P3GLEG you should be able to use `className` in your link schema from v. 0.2.1 on...  

Please check the doc: https://antonioru.github.io/beautiful-react-diagrams/#/Linking%20nodes
