### ISSUE TITLE
Attempted import error: 'createSchema', 'useSchema' is not exported from 'beautiful-react-diagrams'

### ISSUE THREAD

**Issue by tinspham209** [antonioru/beautiful-react-diagrams#32]
Im read the part `Customisation` in document
https://antonioru.github.io/beautiful-react-diagrams/#/Customisation

version: ` beautiful-react-diagrams@0.3.0`

Code is:
```js
import Diagram, { createSchema, useSchema } from "beautiful-react-diagrams";
```

and issues:
```js
Attempted import error: 'createSchema' is not exported from 'beautiful-react-diagrams'
```
```js
Attempted import error: 'useSchema ' is not exported from 'beautiful-react-diagrams'
```

i was temporary fixed it by add the `/index` to import: `"beautiful-react-diagrams/index"`

**Comment by antonioru** [comment]
Hello @tinspham209 

thank you very much for opening this issue. 

I just tried to create a new project using @create-react-app and then I've installed the library via npm. 
I tried to replicate your bug but everything seems working quite fine. 

Can you please be sure you've installed the latest version (0.3.0)? 

Also can you please provide your webpack configuration?

Are you using plain JS or are you using TS?

**Comment by tinspham209** [comment]
Im was try reinstall `npm install` and it seems working fine. Thank you bro. 😉

**Comment by antonioru** [comment]
@tinspham209 thank you very much!
