### ISSUE TITLE
Removing linked node cause 'undefined entity' error

### ISSUE THREAD

**Issue by Lindsay89** [antonioru/beautiful-react-diagrams#33]
**Describe the bug**
When removing a node linked to another one, the library rise an 'undefined entity' error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a schema with different nodes, having a button to remove the node itself.
2. Link one node to another one
3. Remove one of the two linked nodes

**Expected behavior**
Removing a linked node shouldn't cause the application to stop working properly.

**Comment by antonioru** [comment]
Closed by #34
