### ISSUE TITLE
Is it possible to pass in the links array to the render?

### ISSUE THREAD

**Issue by joancc** [antonioru/beautiful-react-diagrams#49]
Thanks for a great library!

I'm trying to update the rendered nodes using values from incoming connections. Can I get access to the links or the schema from inside the renderer?

Thanks!

**Comment by antonioru** [comment]
Hi @joancc 
Nope, at the moment it's not possible to access the schema from inside the renderer, but I think you can solve it by simply pass the schema as a prop to your own Node renderer or am I missing something? 

Please feel free to post your code (please use (codesandbox)[https://codesandbox.io/] or something similar)

**Comment by joancc** [comment]
Totally missed that. Should work. I'll post a sandbox if anything comes up. Thanks!

**Comment by antonioru** [comment]
@joancc 
I think you missed it because the documentation is not really clear, my bad. 
I'll re-write it using GitHub and I'll probably use `styleguidist` for examples only
