### ISSUE TITLE
Not able to render new nodes from outside the component

### ISSUE THREAD

**Issue by thelicato** [antonioru/beautiful-react-diagrams#5]
First of all I wanna say that those diagrams are truly 'beautiful'!
Then I wanna warn you that it is not possible to edit the content of the Diagram from outside the component. For example I added a button to add a new Node in the canvas and even if the schema gets updated the canvas does not change until I make something on the canvas itself (for example moving an already present node or trying to attach some links).
I hope I am completely stupid and there is a simple way to do it.
Nice work and thank you!

**Comment by antonioru** [comment]
Hello @the-licato 
thank you... also best nick name ever. :)) 
I'm not sure I understood the problem you're pointing out, can you please provide any example?

**Comment by the-licato** [comment]
AHAHA thanks
I provided you an example of what I'm trying to accomplish: https://gist.github.com/the-licato/72653e9746ec0a589907c704c858204f

I also have to say that if I use the setSchema with another schema defined previously (different from the current) it does work.

**Comment by antonioru** [comment]
> AHAHA thanks
> I provided you an example of what I'm trying to accomplish: https://gist.github.com/the-licato/72653e9746ec0a589907c704c858204f
> 
> I also have to say that if I use the setSchema with another schema defined previously (different from the current) it does work.

Ok, your example's quite clear. 
I think this is a bug with the library itself, probably a shallow comparison must be replaced with a deep comparison somewhere... 

I'll look into it soon, unfortunately I can't promise a fix date as I'm currently working on other projects (this one is still a priority tho) in the meanwhile PR are absolutely welcome!

**Comment by the-licato** [comment]
For now I solved deep-cloning the _schema_ Object before using the _setSchema_. I'll make a PR as soon as possible

**Comment by antonioru** [comment]
@antonioru that would be really appreciated! 
thank you man

**Comment by volkan-a** [comment]
> AHAHA thanks
> I provided you an example of what I'm trying to accomplish: https://gist.github.com/the-licato/72653e9746ec0a589907c704c858204f
> 
> I also have to say that if I use the setSchema with another schema defined previously (different from the current) it does work.

The link is dead. I think that I have similar problem. Do you keep it already?

**Comment by antonioru** [comment]
@volkan-a @thelicato 
I'm not sure the bug is the same, perhpas @thelicato can provide the link again? :)

**Comment by thelicato** [comment]
> 
> 
> > AHAHA thanks
> > I provided you an example of what I'm trying to accomplish: https://gist.github.com/the-licato/72653e9746ec0a589907c704c858204f
> > I also have to say that if I use the setSchema with another schema defined previously (different from the current) it does work.
> 
> The link is dead. I think that I have similar problem. Do you keep it already?

Sorry for not responding right away. I changed my nickname from "the-licato" to "thelicato" so also the link changed, here is the working link:
https://gist.github.com/thelicato/72653e9746ec0a589907c704c858204f

**Comment by antonioru** [comment]
> > > AHAHA thanks
> > > I provided you an example of what I'm trying to accomplish: https://gist.github.com/the-licato/72653e9746ec0a589907c704c858204f
> > > I also have to say that if I use the setSchema with another schema defined previously (different from the current) it does work.
> > 
> > 
> > The link is dead. I think that I have similar problem. Do you keep it already?
> 
> Sorry for not responding right away. I changed my nickname from "the-licato" to "thelicato" so also the link changed, here is the working link:
> https://gist.github.com/thelicato/72653e9746ec0a589907c704c858204f

I still think you have the best nickname in all the open source world and beyond :))

Thank you... I'll look into it soon

**Comment by antonioru** [comment]
@thelicato in case you need updates of this bug fix, here's the news:

https://github.com/antonioru/beautiful-react-diagrams/issues/6#issuecomment-699528810
